<?php

return [
    'public'=>'-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuR6v9Gu4N30fWOyLXjqT
PRSIKHJgWv1e05FEV3U/uctzqVRA/xRskPlqAVouW8pugoE5aeWzOkL03kAKFTbw
8kY8QeHRDQYZbPxq/QdSQXLhuqZtUbos4bvDbHy+YYgm8mRs0ruy+yyms+Oe0aCd
NaR+6fCFSsSXVtbzbE4gi4Ey4I3j5Dv4U0CTMDujL156UN1YiPJBAk4VUpZIa8+F
L3np5iVwWqKdN/DFtmNFbVVhWgwXSfhxTerbnioSBBm4JAf/08hgbjwEuFw3uzEF
c4PDlM/DQBa1nCQZlVHqfKogycFZtpuQLzIlBzeElcpOcIFWel7RnorjmTFHwkHj
NwIDAQAB
-----END PUBLIC KEY-----'
    ];